# -*- coding: utf-8 -*-
"""fibonacci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lw4th0gdQfa3O2XrGEU_pQIGQ165EINi
"""

# function for iteratively calculating the nth Fibonacci Numbers
def fibonacci(n):
  if n<0:
    print("Please enter a non-negative number")
    return None
  elif n == 0:
    return 0
  elif n == 1:
    return 1
  else:
    x, y = 0, 1
    for i in range(2, n + 1):
      z = x + y
      x = y
      y = z
    return y

# user input
n = int(input("Enter the number of terms in the Fibonacci sequence: "))

# printing the sequence
for i in range(n):
  print(fibonacci(i), end=" ")