# -*- coding: utf-8 -*-
"""positive_numbers_in_a_range.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BxwAoXZF4s5BnGmRuTLOoynwHQ83lWEk
"""

# function to print all the positive numbers in a given range
def positive_numbers(numbers):
  for n in numbers:
    if n > 0:
      print(n, end=" ")

# sample lists:
list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]

# printing the positive numbers
positive_numbers(list1)
print("\n")
positive_numbers(list2)