# -*- coding: utf-8 -*-
"""SetOperations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdQfleQuuMBCKTJ5biNlEtVTSnh4-Ond
"""

#function for operating upon the sets
def set_operations(set1, set2):

  print("Set E:", set1)
  print("Set N:", set2)

  #Union
  union = set1.union(set2)
  print("Union of E and N is", union)

  #Intersection
  intersection = set1.intersection(set2)
  print("Intersection of E and N is", intersection)

  #difference
  difference_1 = set1.difference(set2)
  difference_2 = set2.difference(set1)
  print("Difference of E and N is", difference_1)
  print("Difference of N and E is", difference_2)

  #symmetric difference
  symmetric_difference = set1.symmetric_difference(set2)
  print("Symmetric difference of E and N is", symmetric_difference)

#set defination
set1 = {0, 2, 4, 6, 8}
set2 = {1, 2, 3, 4, 5}

#operations
set_operations(set1, set2)